import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProvidersContainer from "@/features/providers/ProvidersContainer";
import Navbar from "@/features/navbar/Navbar";
import DeleteAccountConfirmation from "@/features/auth/delete-account/DeleteAccountConfirmation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProvidersContainer>
          {children}
          <Navbar />
          <DeleteAccountConfirmation />
          <div id="clerk-captcha" />
        </ProvidersContainer>
      </body>
    </html>
  );
}
